# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ThematicMapLoaderDialog
                                 A QGIS plugin
 Plugin pro prohlížení a přidávání tematických map
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-11-15
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Stikova
        email                : stika.elii@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'thematic_map_loader_dialog_base.ui'))


class ThematicMapLoaderDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(ThematicMapLoaderDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

# ---import JSON---
import os
import json
from qgis.PyQt import uic, QtWidgets
from qgis.PyQt.QtCore import Qt
from qgis.PyQt.QtWidgets import QTreeWidgetItem, QMessageBox
from qgis.core import QgsRasterLayer, QgsProject

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'thematic_map_loader_dialog_base.ui'))

class ThematicMapLoaderDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        super(ThematicMapLoaderDialog, self).__init__(parent)
        self.setupUi(self)

        # --- cesta k JSON ---
        self.json_path = os.path.join(os.path.dirname(__file__), 'maps.json')
        self.layers_data = []

        # --- načtení JSON ---
        if os.path.exists(self.json_path):
            with open(self.json_path, "r", encoding="utf-8") as f:
                self.layers_data = json.load(f)

        # --- naplnění QTreeWidget vrstev podle kategorií ---
        self.treeWidget_layers.clear()  # v .ui pojmenuj widget jako treeWidget_layers
        categories = {}
        for layer in self.layers_data:
            category = layer.get("category", "Nezařazeno")
            if category not in categories:
                cat_item = QTreeWidgetItem([category])
                cat_item.setFlags(cat_item.flags() & ~Qt.ItemIsSelectable)
                self.treeWidget_layers.addTopLevelItem(cat_item)
                categories[category] = cat_item

            layer_item = QTreeWidgetItem([layer["name"]])
            layer_item.setCheckState(0, Qt.Unchecked)
            categories[category].addChild(layer_item)

        self.treeWidget_layers.expandAll()  # rozbalíme všechny kategorie

        # --- propojení tlačítek OK / Cancel ---
        self.button_box.accepted.connect(self.add_selected_layers)
        self.button_box.rejected.connect(self.reject)

    def add_selected_layers(self):
        """Přidá vybrané vrstvy do QGIS projektu."""
        for category_index in range(self.treeWidget_layers.topLevelItemCount()):
            cat_item = self.treeWidget_layers.topLevelItem(category_index)
            for i in range(cat_item.childCount()):
                item = cat_item.child(i)
                if item.checkState(0) == Qt.Checked:
                    layer_name = item.text(0)
                    # najdeme data v JSON podle jména
                    layer_info = next((l for l in self.layers_data if l["name"] == layer_name), None)
                    if not layer_info:
                        continue
                    try:
                        layer_type = layer_info["type"].upper()

                        if layer_type == "WMS":
                            uri = f"{layer_info['url']}?layers={layer_info['layers']}&crs=EPSG:3857&format=image/png"
                            rlayer = QgsRasterLayer(uri, layer_name, "wms")
                        elif layer_type == "WMTS":
                            uri = layer_info["url"]
                            rlayer = QgsRasterLayer(uri, layer_name, "wmts")
                        elif layer_type == "XYZ" or ("tilecache" in layer_info["url"].lower()):
                            uri = layer_info["url"]
                            rlayer = QgsRasterLayer(f"type=xyz&url={uri}", layer_name, "xyz")
                        else:
                            continue

                        if rlayer.isValid():
                            QgsProject.instance().addMapLayer(rlayer)
                        else:
                            QMessageBox.warning(self, "Chyba vrstvy", f"Nelze načíst vrstvu: {layer_name}")
                    except Exception as e:
                        QMessageBox.warning(self, "Chyba", f"Chyba při načítání vrstvy {layer_name}:\n{str(e)}")

        self.accept()

